### ISSUE TITLE
How to use this?!?!?!?!

### ISSUE THREAD

**Issue by Thundros** [AidanNelson/threejs-webrtc#1]
Hi @AidanNelson : Just wanted to know how to access this WITHOUT having to type in "npm start" or "npm run". I can run the server just fine, but I'm getting polling errors when I navigate to the example. Any help is GREATLY appreciated!

Thank you so kindly!

**Comment by AidanNelson** [comment]
Hi @Thundros, what errors are you getting?

**Comment by Thundros** [comment]
@AidanNelson : 
`DevTools` failed to parse SourceMap: http://localhost:8080/headless-content.js.map
index.js:51 Window loaded.
index.js:75 Failed to get user media!
index.js:76 DOMException: Requested device not found
getMedia @ index.js:76
async function (async)
getMedia @ index.js:73
window.onload @ index.js:54
load (async)
(anonymous) @ index.js:50
index.js:98 Initializing socket.io...
index.js:341 Creating three.js scene...
scene.js:296 Uncaught (in promise) TypeError: Cannot read property 'getVideoTracks' of null
    at createLocalVideoElement (scene.js:296)
    at Scene.addSelf (scene.js:91)
    at new Scene (scene.js:31)
    at createScene (index.js:342)
    at window.onload (index.js:60)
createLocalVideoElement @ scene.js:296
addSelf @ scene.js:91
Scene @ scene.js:31
createScene @ index.js:342
window.onload @ index.js:60
async function (async)
window.onload @ index.js:54
load (async)
(anonymous) @ index.js:50
index.js:83 GET http://localhost:82/socket.io/?EIO=3&transport=polling&t=N5_mYfJ 404 (Not Found)
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doPoll @ index.js:83
r.poll @ index.js:83
r.doOpen @ index.js:83
r.open @ index.js:83
r.open @ index.js:83
r @ index.js:83
r @ index.js:83
r.open.r.connect @ index.js:83
r @ index.js:83
r @ index.js:83
r @ index.js:83
initSocketConnection @ index.js:99
window.onload @ index.js:57
async function (async)
window.onload @ index.js:54
load (async)
(anonymous) @ index.js:50
index.js:83 GET http://localhost:82/socket.io/?EIO=3&transport=polling&t=N5_mYzx 404 (Not Found)
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doPoll @ index.js:83
r.poll @ index.js:83
r.doOpen @ index.js:83
r.open @ index.js:83
r.open @ index.js:83
r @ index.js:83
r @ index.js:83
r.open.r.connect @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
r.reconnect @ index.js:83
r.maybeReconnectOnOpen @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
i.onError @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
hasXDR.e.onreadystatechange @ index.js:83
XMLHttpRequest.send (async)
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doPoll @ index.js:83
r.poll @ index.js:83
r.doOpen @ index.js:83
r.open @ index.js:83
r.open @ index.js:83
r @ index.js:83
r @ index.js:83
r.open.r.connect @ index.js:83
r @ index.js:83
r @ index.js:83
r @ index.js:83
initSocketConnection @ index.js:99
window.onload @ index.js:57
async function (async)
window.onload @ index.js:54
load (async)
(anonymous) @ index.js:50
index.js:83 GET http://localhost:82/socket.io/?EIO=3&transport=polling&t=N5_mZPG 404 (Not Found)
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doPoll @ index.js:83
r.poll @ index.js:83
r.doOpen @ index.js:83
r.open @ index.js:83
r.open @ index.js:83
r @ index.js:83
r @ index.js:83
r.open.r.connect @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
r.reconnect @ index.js:83
(anonymous) @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
i.onError @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
hasXDR.e.onreadystatechange @ index.js:83
XMLHttpRequest.send (async)
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doPoll @ index.js:83
r.poll @ index.js:83
r.doOpen @ index.js:83
r.open @ index.js:83
r.open @ index.js:83
r @ index.js:83
r @ index.js:83
r.open.r.connect @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
r.reconnect @ index.js:83
r.maybeReconnectOnOpen @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
i.onError @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
hasXDR.e.onreadystatechange @ index.js:83
XMLHttpRequest.send (async)
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doPoll @ index.js:83
r.poll @ index.js:83
r.doOpen @ index.js:83
r.open @ index.js:83
r.open @ index.js:83
r @ index.js:83
r @ index.js:83
r.open.r.connect @ index.js:83
r @ index.js:83
r @ index.js:83
r @ index.js:83
initSocketConnection @ index.js:99
window.onload @ index.js:57
async function (async)
window.onload @ index.js:54
load (async)
(anonymous) @ index.js:50
index.js:83 GET http://localhost:82/socket.io/?EIO=3&transport=polling&t=N5_maL3 404 (Not Found)`

And yes, I did install the node modules via `npm install .`

**Comment by AidanNelson** [comment]
Do you have a webcam?  The error is saying that [Navigator.GetUserMedia()](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia) failed while requesting access to your webcam and microphone.  You might try explicitly enabling the webcam / microphone in your browser if it doesn't ask for it.

**Comment by Thundros** [comment]
@AidanNelson : I do have a webcam.

**Comment by AidanNelson** [comment]
> You might try explicitly enabling the webcam / microphone in your browser if it doesn't ask for it.

Have you tried this?

**Comment by Thundros** [comment]
@AidanNelson : How? I have chrome.

**Comment by AidanNelson** [comment]
The button to the left of the address in the address bar (normally displays a lock icon if you are on a secure -- https -- site). Or go to `chrome://settings/content/siteDetails?site=http://localhost:1989` in your address bar.

**Comment by Thundros** [comment]
@AidanNelson : I just tried to enable it & still I'm getting the error : 

`index.js:83 GET http://localhost:82/socket.io/?EIO=3&transport=polling&t=N63OhS9 404 (Not Found)`

The server is on

**Comment by AidanNelson** [comment]
Hmm... I'm not sure.  It seems to be related to this StackOverflow thread, though: https://stackoverflow.com/questions/16981396/get-http-localhost3000-socket-io-socket-io-js-404-not-found
Please post back if you find any results.

**Comment by Thundros** [comment]
@AidanNelson : So I guess it does work TO AN EXTENT. I plugged in an external webcam, refreshed the server & client & it worked. KINDA. But here's the problem I am now getting : 

```
Window loaded.
index.js:98 Initializing socket.io...
index.js:341 Creating three.js scene...
three.min.js:988 THREE.Material: .overdraw has been removed.
get @ three.min.js:988
setValues @ three.min.js:498
Oa @ three.min.js:13
makeVideoTextureAndMaterial @ scene.js:351
addSelf @ scene.js:93
Scene @ scene.js:31
createScene @ index.js:342
window.onload @ index.js:60
async function (async)
window.onload @ index.js:54
load (async)
(anonymous) @ index.js:50
three.min.js:498 THREE.MeshBasicMaterial: 'overdraw' is not a property of this material.
setValues @ three.min.js:498
Oa @ three.min.js:13
makeVideoTextureAndMaterial @ scene.js:351
addSelf @ scene.js:93
Scene @ scene.js:31
createScene @ index.js:342
window.onload @ index.js:60
async function (async)
window.onload @ index.js:54
load (async)
(anonymous) @ index.js:50
index.js:83 GET http://localhost:82/socket.io/?EIO=3&transport=polling&t=N63q49t 404 (Not Found)
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doPoll @ index.js:83
r.poll @ index.js:83
r.doOpen @ index.js:83
r.open @ index.js:83
r.open @ index.js:83
r @ index.js:83
r @ index.js:83
r.open.r.connect @ index.js:83
r @ index.js:83
r @ index.js:83
r @ index.js:83
initSocketConnection @ index.js:99
window.onload @ index.js:57
async function (async)
window.onload @ index.js:54
load (async)
(anonymous) @ index.js:50
DevTools failed to parse SourceMap: http://localhost:8080/headless-content.js.map
index.js:83 GET http://localhost:82/socket.io/?EIO=3&transport=polling&t=N63q4Sk 404 (Not Found)
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doPoll @ index.js:83
r.poll @ index.js:83
r.doOpen @ index.js:83
r.open @ index.js:83
r.open @ index.js:83
r @ index.js:83
r @ index.js:83
r.open.r.connect @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
r.reconnect @ index.js:83
r.maybeReconnectOnOpen @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
i.onError @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
hasXDR.e.onreadystatechange @ index.js:83
XMLHttpRequest.send (async)
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doPoll @ index.js:83
r.poll @ index.js:83
r.doOpen @ index.js:83
r.open @ index.js:83
r.open @ index.js:83
r @ index.js:83
r @ index.js:83
r.open.r.connect @ index.js:83
r @ index.js:83
r @ index.js:83
r @ index.js:83
initSocketConnection @ index.js:99
window.onload @ index.js:57
async function (async)
window.onload @ index.js:54
load (async)
(anonymous) @ index.js:50
index.js:83 GET http://localhost:82/socket.io/?EIO=3&transport=polling&t=N63q4_i 404 (Not Found)
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doPoll @ index.js:83
r.poll @ index.js:83
r.doOpen @ index.js:83
r.open @ index.js:83
r.open @ index.js:83
r @ index.js:83
r @ index.js:83
r.open.r.connect @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
r.reconnect @ index.js:83
(anonymous) @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
i.onError @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
hasXDR.e.onreadystatechange @ index.js:83
XMLHttpRequest.send (async)
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doPoll @ index.js:83
r.poll @ index.js:83
r.doOpen @ index.js:83
r.open @ index.js:83
r.open @ index.js:83
r @ index.js:83
r @ index.js:83
r.open.r.connect @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
r.reconnect @ index.js:83
r.maybeReconnectOnOpen @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
i.onError @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
hasXDR.e.onreadystatechange @ index.js:83
XMLHttpRequest.send (async)
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doPoll @ index.js:83
r.poll @ index.js:83
r.doOpen @ index.js:83
r.open @ index.js:83
r.open @ index.js:83
r @ index.js:83
r @ index.js:83
r.open.r.connect @ index.js:83
r @ index.js:83
r @ index.js:83
r @ index.js:83
initSocketConnection @ index.js:99
window.onload @ index.js:57
async function (async)
window.onload @ index.js:54
load (async)
(anonymous) @ index.js:50
index.js:83 GET http://localhost:82/socket.io/?EIO=3&transport=polling&t=N63q5n4 404 (Not Found)
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doPoll @ index.js:83
r.poll @ index.js:83
r.doOpen @ index.js:83
r.open @ index.js:83
r.open @ index.js:83
r @ index.js:83
r @ index.js:83
r.open.r.connect @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
r.reconnect @ index.js:83
(anonymous) @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
i.onError @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
hasXDR.e.onreadystatechange @ index.js:83
XMLHttpRequest.send (async)
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doPoll @ index.js:83
r.poll @ index.js:83
r.doOpen @ index.js:83
r.open @ index.js:83
r.open @ index.js:83
r @ index.js:83
r @ index.js:83
r.open.r.connect @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
r.reconnect @ index.js:83
(anonymous) @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
i.onError @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
hasXDR.e.onreadystatechange @ index.js:83
XMLHttpRequest.send (async)
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doPoll @ index.js:83
r.poll @ index.js:83
r.doOpen @ index.js:83
r.open @ index.js:83
r.open @ index.js:83
r @ index.js:83
r @ index.js:83
r.open.r.connect @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
r.reconnect @ index.js:83
r.maybeReconnectOnOpen @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
i.onError @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
hasXDR.e.onreadystatechange @ index.js:83
XMLHttpRequest.send (async)
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doPoll @ index.js:83
r.poll @ index.js:83
r.doOpen @ index.js:83
r.open @ index.js:83
r.open @ index.js:83
r @ index.js:83
r @ index.js:83
r.open.r.connect @ index.js:83
r @ index.js:83
r @ index.js:83
r @ index.js:83
initSocketConnection @ index.js:99
window.onload @ index.js:57
async function (async)
window.onload @ index.js:54
load (async)
(anonymous) @ index.js:50
index.js:83 GET http://localhost:82/socket.io/?EIO=3&transport=polling&t=N63q7A7 404 (Not Found)
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doPoll @ index.js:83
r.poll @ index.js:83
r.doOpen @ index.js:83
r.open @ index.js:83
r.open @ index.js:83
r @ index.js:83
r @ index.js:83
r.open.r.connect @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
r.reconnect @ index.js:83
(anonymous) @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
i.onError @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
hasXDR.e.onreadystatechange @ index.js:83
XMLHttpRequest.send (async)
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doPoll @ index.js:83
r.poll @ index.js:83
r.doOpen @ index.js:83
r.open @ index.js:83
r.open @ index.js:83
r @ index.js:83
r @ index.js:83
r.open.r.connect @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
r.reconnect @ index.js:83
(anonymous) @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
i.onError @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
hasXDR.e.onreadystatechange @ index.js:83
XMLHttpRequest.send (async)
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doPoll @ index.js:83
r.poll @ index.js:83
r.doOpen @ index.js:83
r.open @ index.js:83
r.open @ index.js:83
r @ index.js:83
r @ index.js:83
r.open.r.connect @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
r.reconnect @ index.js:83
(anonymous) @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
i.onError @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
hasXDR.e.onreadystatechange @ index.js:83
XMLHttpRequest.send (async)
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doPoll @ index.js:83
r.poll @ index.js:83
r.doOpen @ index.js:83
r.open @ index.js:83
r.open @ index.js:83
r @ index.js:83
r @ index.js:83
r.open.r.connect @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
r.reconnect @ index.js:83
r.maybeReconnectOnOpen @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
i.onError @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
hasXDR.e.onreadystatechange @ index.js:83
XMLHttpRequest.send (async)
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doPoll @ index.js:83
r.poll @ index.js:83
r.doOpen @ index.js:83
r.open @ index.js:83
r.open @ index.js:83
r @ index.js:83
r @ index.js:83
r.open.r.connect @ index.js:83
r @ index.js:83
r @ index.js:83
r @ index.js:83
initSocketConnection @ index.js:99
window.onload @ index.js:57
async function (async)
window.onload @ index.js:54
load (async)
(anonymous) @ index.js:50
```

**Comment by AidanNelson** [comment]
@Thundros it would be more helpful if you just linked the relevant error message rather than the whole console log.  Also, you can format block text as code using triple backticks before and after: ```

You could try the solution posted [here](https://stackoverflow.com/questions/16981396/get-http-localhost3000-socket-io-socket-io-js-404-not-found) which is basically to switch the line initializing the socket object [here](https://github.com/AidanNelson/threejs-webrtc/blob/15f7dddd07895a2bf2db662fa8a8be4fcd6b5917/public/js/index.js#L99) to  `socket = io().connect("http://localhost:1989");`

**Comment by Thundros** [comment]
@AidanNelson : Which line would I change?

**Comment by Thundros** [comment]
@AidanNelson : Hello?

**Comment by Thundros** [comment]
@AidanNelson : I do not understand where to put this new code.

**Comment by AidanNelson** [comment]
@Thundros I have several updates planned for this repo, including fixing this bug, but won't be able to address them for a few weeks.

**Comment by Thundros** [comment]
@AidanNelson : ok, i'll check back in a few weeks :) Thanks again brother! <3

**Comment by Thundros** [comment]
Hi @AidanNelson ! Can you add that server fix so that I may try this demo?

Thank you SO much! <3

**Comment by Thundros** [comment]
@AidanNelson : Hello?

**Comment by Thundros** [comment]
???

**Comment by Thundros** [comment]
@AidanNelson : Hello?

**Comment by omarolaes** [comment]
Hello, I'm having the same issue with vultr on ubuntu with this error:
And it neves asks me for the webcam, only on localhost works perfectly.

scene.js:379 Uncaught (in promise) TypeError: Cannot read property 'getVideoTracks' of null
    at createLocalVideoElement (scene.js:379)
    at Scene.addSelf (scene.js:153)
    at new Scene (scene.js:31)
    at createScene (index.js:343)
    at window.onload (index.js:60)

**Comment by AidanNelson** [comment]
The client-side code will need HTTPs if running on a server because it requests user media (webcam & microphone).  I will add something in the README on my next update.
